# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181210_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('path_1', models.CharField(max_length=100)),
                ('path_2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('store', models.IntegerField(max_length=100)),
                ('explain', models.CharField(max_length=100)),
            ],
        ),
    ]
