# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='explain',
            new_name='instr',
        ),
    ]
