# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.IntegerField(default=0),
        ),
    ]
